# Generated by Django 5.1.2 on 2024-12-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Watch',
            new_name='Watchs',
        ),
    ]
