# Generated by Django 5.1.5 on 2025-01-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_watch_order_watchs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='Watch_image',
        ),
        migrations.AddField(
            model_name='watch',
            name='category',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Sport', 'Sport'), ('Smart', 'Smart')], default='Luxury', max_length=20),
        ),
        migrations.AddField(
            model_name='watch',
            name='watch_image',
            field=models.ImageField(blank=True, null=True, upload_to='watch_images'),
        ),
    ]
