# Generated by Django 5.1.5 on 2025-01-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_watch_watch_image_watch_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='watch_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='watch_images'),
        ),
        migrations.AddField(
            model_name='watch',
            name='watch_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='watch_images'),
        ),
    ]
