# Generated by Django 5.1.5 on 2025-01-31 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_watch_watch_image_2_watch_watch_image_3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Watchs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.watch')),
            ],
        ),
    ]
