# Generated by Django 5.1.5 on 2025-02-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_order_watchs_remove_order_quantity_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='watch_image_2',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='watch_image_3',
        ),
    ]
